### ISSUE TITLE
Embedly does not load on wordpress 4.0

### ISSUE THREAD

**Issue by NeoCsatornaja** [embedly/embedly_wordpress_plugin#10]
Hy!
I use this wordpress plugin and just wont load.
I  click for the embedly button, the lightbox is shows, and there noting loading.
I use latest version of embed.ly wordpress plugin.

**Comment by NeoCsatornaja** [comment]
And closed becouse?

**Comment by screeley** [comment]
We no longer support the lightbox, it caused too many issue with TinyMCE and compatibility across versions of Wordpress.
