### ISSUE TITLE
validate_api_key is fired on each frontend request

### ISSUE THREAD

**Issue by rinatkhaziev** [embedly/embedly_wordpress_plugin#15]
Hi, 

`validate_api_key` method is hooked to plugins_loaded, which fires on each request, making a remote request which is detrimental to site performance. I'm not sure why it's done this way, since I'm not familiar with the platform, but I moved it admin_init hook, which is still suboptimal but at least it's not going to affect frontend. Probably it's better to move it to a wp cron hook. After all, how often keys are getting invalidated?

Cheers,
Rinat.

**Comment by stiteler** [comment]
Hi Rinat,

Thanks again for your feedback, I'm testing a change currently that uses wordpress cron to do the validation. 

-Chris

**Comment by stiteler** [comment]
See [05a4803](https://github.com/embedly/embedly_wordpress_plugin/commit/05a480399152dda39d4e2b75f86b8564e7ae8241)
